### PR TITLE
config: Check if any classes are duplicated

### PR DESCRIPTION
**Pull request by PabstMirror**
Catches any duplicate class
e.g.
```
class a;
class a {};

class b {};
class b {};
```

### CODE REVIEW

**Comment by BrettMayson** [comment]
```
class a;
class a {};
```

That's definitely an issue, are you sure the other one is? From some basic testing when I created that error it worked fine, the error is only to prevent human error.

**Comment by PabstMirror** [comment]
```
class b {};
class b {};
```
causes a crash on startup (same as `a` example)
```
ErrorMessage: File x\cba\addons\ai\config.cpp, line 27: .b: Member already defined.
Application terminated intentionally
```

**Comment by BrettMayson** [comment]
Alright, Interesting. I remember us talking about this in Discord and I tested it

**Review by BrettMayson — COMMENTED** [review]
Should change the error code and rename the files to match what is actually going on now

**Pull request merged**
