### PR TITLE
p3d, missing textures & materials

### PR DESCRIPTION
**Pull request by BrettMayson**
```toml
[hemtt.build]
pdrive = "require"
```
1. Will use a mounted P:\ drive first if one exists
2. Will look for a setup but unmounted P drive from the Arma 3 Tools settings
3. Will use an Arma 3 steam installation and extract needed files to %temp%\hemtt

### CODE REVIEW

**Comment by BrettMayson** [comment]
@mike-mf for testing too please

**Comment by BrettMayson** [comment]
ok I should be done pushing this now :| fixed the linux issue very efficiently in 3 commits

**Comment by jonpas** [comment]
Mike has I think, I'll try to do it today.

**Comment by BrettMayson** [comment]
Going to merge as I want to make some internal changes on main and don't feel like dealing with a merge later, I think this should be good to go. We can use the issue #596 to finish confirming this

**Pull request merged**
