### PR TITLE
Fix __LINE__ and __FILE__ builtins

### PR DESCRIPTION
**Pull request by veteran29**
__LINE__ returns the line the macro was used in, not defined

__FILE__ should is quoted and returns the file the macro was used in, not defined

### CODE REVIEW

**Comment by BrettMayson** [comment]
> TODO add $PBOPREFIX$ of the current file somehow

How exactly do you mean?

**Comment by veteran29** [comment]
> How exactly do you mean?

I've added example file to `bravo` test addon in ad6b4e9.

The file is preprocessed to:
```sqf
"include/c/d/header.hpp";
1;



"/addons/main/functions/fnc_test.sqf";
4;

systemChat "test";
```

expected output:
```sqf
"/c/d/header.hpp";
1;



"/a/b/addons/main/functions/fnc_test.sqf";
4;

systemChat "test";
```

I've managed to fix it locally for files in the addon dir but not sure how to handle includes and I think my approach is invalid. I guess the `resolver` should give this info to the `context` somehow.

**Comment by veteran29** [comment]
After additional testing:
```
#include "functions\test.hpp"
```
gives:
```sqf
"functions\test.hpp";
```
So I guess the __FILE__ builtin should just give current include path.

**Comment by BrettMayson** [comment]
Closing since the preprocessor was rewritten

**Pull request closed without merging**
