### PR TITLE
Binarize: fix copy files from addons folder path 

### PR DESCRIPTION
**Pull request by jonpas**
Fix path from #590. Tested only on CUP, ~~it might go a folder too high in other mods? That would still work though~~.

### CODE REVIEW

**Comment by BrettMayson** [comment]
Using the prefix and then just parenting it if it, is it not better to just remove the prefix and patent?

**Comment by jonpas** [comment]
> Using the prefix and then just parenting out of it, is it not better to just remove the prefix and parent?

That results in `%tmp%/hemtt/source/<file>` instead of `%tmp%/hemtt/source/<mod>/<file>`.

**Comment by BrettMayson** [comment]
That'd still work though, at least for model.cfg

I just want to make sure we avoid another issue of the prefixes being weird and it ends up somewhere inaccessible

**Comment by jonpas** [comment]
> That'd still work though, at least for model.cfg
> 
> I just want to make sure we avoid another issue of the prefixes being weird and it ends up somewhere inaccessible

Correct, it did work. I will adjust then.

**Review by BrettMayson — APPROVED** [review]

**Pull request merged**
